### ISSUE TITLE
Setting abstract attribute of class explicitly to False causes problems in parsing of model

### ISSUE THREAD

**Issue by LarsDeLeeuw** [joeriexelmans/muMLE#1]
**Input Meta Model:** 
`
"""
Factory:Class {
        abstract = False;
}
"""
`
**Input Model:**
`
"""
factory1:Factory
"""
`
**Output:**
`
Loading meta-meta-model...
OK
Is our meta-meta-model a valid class diagram?
OK

Parsing 'factory' meta-model...
OK
Is our 'factory' meta-model a valid class diagram?
OK

Parsing 'factory' model...
Traceback (most recent call last):
  File "/home/flakers/Documents/projects/muMLE/.venv/lib/python3.12/site-packages/lark/visitors.py", line 124, in _call_userfunc
    return f(children)
           ^^^^^^^^^^^
  File "/home/flakers/Documents/projects/muMLE/concrete_syntax/textual_od/parser.py", line 73, in object
    obj_node = od.create_object(obj_name, type_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flakers/Documents/projects/muMLE/services/od.py", line 36, in create_object
    return self._create_object(name, class_node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flakers/Documents/projects/muMLE/services/od.py", line 47, in _create_object
    is_abstract, _ = read_primitive_value(self.bottom, slot, self.type_model)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flakers/Documents/projects/muMLE/services/od.py", line 382, in read_primitive_value
    raise Exception("Unimplemented type:", typ_name)
Exception: ('Unimplemented type:', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flakers/Documents/projects/muMLE/examples/conformance/factory.py", line 102, in <module>
    woods_m = parser.parse_od(
              ^^^^^^^^^^^^^^^^
  File "/home/flakers/Documents/projects/muMLE/concrete_syntax/textual_od/parser.py", line 101, in parse_od
    t = T(visit_tokens=True).transform(tree)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flakers/Documents/projects/muMLE/.venv/lib/python3.12/site-packages/lark/visitors.py", line 161, in transform
    return self._transform_tree(tree)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flakers/Documents/projects/muMLE/.venv/lib/python3.12/site-packages/lark/visitors.py", line 157, in _transform_tree
    return self._call_userfunc(tree, children)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flakers/Documents/projects/muMLE/.venv/lib/python3.12/site-packages/lark/visitors.py", line 128, in _call_userfunc
    raise VisitError(tree.data, tree, e)
lark.exceptions.VisitError: Error trying to process rule "object":

('Unimplemented type:', None)
`
**Defining the Factory class without attributes resolves parsing error**

**Comment by joeriexelmans** [comment]
Thanks for reporting this. I'll fix it asap.

**Comment by joeriexelmans** [comment]
Fixed by https://github.com/joeriexelmans/muMLE/commit/b38d42b5d0e669bd97a0c1276a967ce8831ddd0c
